### ISSUE TITLE
Add support for $string*

### ISSUE THREAD

**Issue by ruppde** [avast/yari#63]
Hello,

yari doesn't support $string* matches in hoovering over conditions. Best way would probably to just show a summary, e.g.:

- No match
- Which ones of $string* matched

**Comment by ruppde** [comment]
Cheap double win would be to enable the hoovering as in the strings section:
1. Possibility to check each element of $string*
2. No need to jump from string to the condition section to check a string or regex

Bonus feature: Visually mark all matching strings in the strings section:

**Comment by MatejKastak** [comment]
Nice suggestions! This however is not supported in YARI, yet.

But you can try to at least get if the whole expression works if you select the parts of the condition.

![image](https://github.com/avast/yari/assets/26434056/98429c59-4cf0-4c02-a866-366da1910a1d)
